sudo: required
services:
  - docker

before_install:
  - docker build -t tislam93/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true tislam93/react-test npm test

after_success:
  - docker build -t tislam93/multi-client ./client
  - docker build -t tislam93/multi-nginx ./nginx
  - docker build -t tislam93/multi-server ./server
  - docker build -t tislam93/multi-worker ./worker    
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to github
  - docker push tislam93/multi-client
  - docker push tislam93/multi-nginx
  - docker push tislam93/multi-server
  - docker push tislam93/multi-worker